import { Issue } from "@/models/issue.model";
import { Project } from "@/models/project.model";
import { Sprint } from "@/models/sprint.model";
import { User } from "@/models/user.model";
import {
  deleteProjectByIdService,
  findProjectByIdService,
} from "@/services/project.service";
import { findUserByIdService } from "@/services/user.service";
import ApiError from "@/utils/ApiError";
import ApiResponse from "@/utils/ApiResponse";
import customError from "@/utils/customError";

// get project with the project id
export async function GET({ params }: { params: { id: string } }) {
  try {
    // getting id from the params
    const { id: projectId } = await params;

    // getting user details and check wether user is in this project or not
    const isUserExist = await User.findById();

    // throwing error if user not exist
    if (!isUserExist) {
      throw new customError("User with this id not found", 404);
    }

    // getting user details and check wether user is member of this project or not
    const isProjectExist = await findProjectByIdService(projectId);

    // finding user id exist in the project member array or not
    const isUserInThisProject = isProjectExist?.members.find(
      (pId: string) => pId.toString() === projectId,
    );

    // throwing error if user is not in the project member array
    if (!isUserInThisProject) {
      throw new customError("User not present in this project", 400);
    }

    // if project fetched then return response
    return ApiResponse({
      statusCode: 200,
      message: "Project details fetched successfully",
      data: isProjectExist,
    });
  } catch (error: unknown) {
    const err = error as { statusCode?: number; message?: string };
    return ApiError({
      statusCode: err?.statusCode || 500,
      error,
      message: err?.message || "Something went wrong",
    });
  }
}

// update project with the project id
export async function PUT() {
  try {
    // checking project exist or not
    // checking user is admin or manager if not then throw error
    // checking user is manager and part of the project or not. if not then throw error.
    // if everything is fine then updating the project and if bug comes then throw error
    // return the result
  } catch (error: unknown) {
    const err = error as { statusCode?: number; message?: string };
    return ApiError({
      statusCode: err?.statusCode || 500,
      error,
      message: err?.message || "Something went wrong",
    });
  }
}

// delete project with the project id
export async function DELETE({ params }: { params: { id: string } }) {
  try {
    // user details is generated by the middleware
    // getting the product id through params
    // checking project exist or not if not then throw error
    // checking user is admin or manager if not then throw error
    // checking user is manager and part of the project or not. if not then throw error.
    // if everything is fine then delete the project and if bug comes then throw error
    // return the result

    // getting id from the params
    const { id: projectId } = await params;

    // find project and getting all details or throwing error using find service
    const isProjectExist = await findProjectByIdService(projectId);

    // finding user id exist in the project member array or not
    const isUserInThisProject = isProjectExist?.members.find(
      (memberId: string) => memberId.toString() === projectId,
    );

    // throwing error if user is not in the project member array
    if (!isUserInThisProject) {
      throw new customError("User not present in this project", 400);
    }

    // deleting all issue in the project
    const isIssuesDeleted = await Issue.find({ projectId });

    // throwing error if issue not deleted
    if (!isIssuesDeleted) {
      throw new customError("Error during removing issues", 400);
    }

    // deleting all sprint in the project
    const isSprintDeleted = await Sprint.find({ projectId });

    // throwing error if sprint not deleted
    if (!isSprintDeleted) {
      throw new customError("Error during removing sprint", 400);
    }

    // deleting project or throwing error using delete service
    const isProjectDeleted = await deleteProjectByIdService(projectId);

    // if project deleted then return response
    return ApiResponse({
      statusCode: 200,
      message: "Project Deleted Successfully",
      data: isProjectDeleted,
    });
  } catch (error: unknown) {
    const err = error as { statusCode?: number; message?: string };
    return ApiError({
      statusCode: err?.statusCode || 500,
      error,
      message: err?.message || "Something went wrong",
    });
  }
}
